#!/usr/bin/env bash

# Update the package list
sudo apt update

# Install Nginx
sudo apt install nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a basic HTML file with the required content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx
sudo /etc/init.d/nginx restart

