#!/usr/bin/env bash
# Script: 0-nginx_likes_port_80
# Description: Debugging Nginx to listen on port 80.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

