#!/usr/bin/env bash
# Display different outputs using while if elif  and else
 
the_count=1
while (( the_count <= 10 ));
do
	if (( the_count == 4 ));
	then	
		echo "bad luck"

	elif (( the_count == 8 ));
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((the_count++))
done
