#!/usr/bin/env bash
# This script configures Nginx to run as nginx user and listen on all active IPs on port 8080

# Backup the original Nginx configuration file
cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak

# Update the Nginx configuration to run as the nginx user and listen on port 8080
sed -i 's/user  nginx;/user  nginx;\n    listen 8080;/g' /etc/nginx/nginx.conf

# Restart Nginx to apply the changes
service nginx restart

# Display Nginx processes
ps auxff | grep ngin[x]

# Check if Nginx is listening on port 8080
nc -z 0 8080
